<a href="https://colab.research.google.com/github/Ayanlola2002/Stutern/blob/master/webscrape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from requests import get
url = 'http://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
response = get(url)
print(response.text[:500])

<!DOCTYPE html>
<html
    xmlns:og="http://ogp.me/ns#"
    xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="apple-itunes-app" content="app-id=342792525, app-argument=imdb:///?src=mdot">



        <script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>

<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle"

In [0]:
from bs4 import BeautifulSoup
html_soup = BeautifulSoup(response.text, 'html.parser')
type(html_soup)

bs4.BeautifulSoup

In [0]:
movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
print(type(movie_containers))
print(len(movie_containers))

<class 'bs4.element.ResultSet'>
50

In [0]:
# Lists to store the scraped data in
names = []
years = []
imdb_ratings = []
metascores = []
votes = []
# Extract data from individual movie container
for container in movie_containers:
# If the movie has Metascore, then extract:
    if container.find('div', class_ = 'ratings-metascore') is not None:

# The name
      name = container.h3.a.text
      names.append(name)
# The year
      year = container.h3.find('span', class_ = 'lister-item-year').text
      years.append(year)
# The IMDB rating
      imdb = float(container.strong.text)
      imdb_ratings.append(imdb)
# The Metascore
      m_score = container.find('span', class_ = 'metascore').text
      metascores.append(int(m_score))
# The number of votes
      vote = container.find('span', attrs = {'name':'nv'})['data-value']
      votes.append(int(vote))

In [0]:
import pandas as pd
test_df = pd.DataFrame({'movie': names,
'year': years,
'imdb': imdb_ratings,
'metascore': metascores,
'votes': votes
})
print(test_df.info())
test_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 5 columns):
movie        43 non-null object
year         43 non-null object
imdb         43 non-null float64
metascore    43 non-null int64
votes        43 non-null int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.8+ KB
None

                                               movie  ...   votes
0                                              Logan  ...  598346
1                                     Thor: Ragnarok  ...  531720
2            Star Wars: Episode VIII - The Last Jedi  ...  523239
3                     Guardians of the Galaxy Vol. 2  ...  522741
4                                       Wonder Woman  ...  515651
5                                            Dunkirk  ...  499401
6                             Spider-Man: Homecoming  ...  470343
7                                            Get Out  ...  442104
8                                                 It  ...  419743
9                                  Blade Runner 2049  ...  411907
10                                       Baby Driver  ...  396081
11         Three Billboards Outside Ebbing, Missouri  ...  380267
12                                    Justice League  ...  353077
13                                The Shape of Water  ...  336665
14                              John Wick: Chapter 2  ...  330713
15                                              Coco  ...  318855
16                    Jumanji: Welcome to the Jungle  ...  284092
17                              Beauty and the Beast  ...  253147
18                                Kong: Skull Island  ...  252170
19                       Kingsman: The Golden Circle  ...  248868
20  Pirates of the Caribbean: Dead Men Tell No Tales  ...  242223
21                                   Alien: Covenant  ...  238502
22                              The Greatest Showman  ...  213731
23                    War for the Planet of the Apes  ...  212852
24                                         Lady Bird  ...  200515
25                                              Life  ...  192141
26                      Murder on the Orient Express  ...  191656
27                           The Fate of the Furious  ...  191303
28                                Ghost in the Shell  ...  185686
29                                        Wind River  ...  183521
30                  King Arthur: Legend of the Sword  ...  178396
31                              Call Me by Your Name  ...  175757
32                            The Hitman's Bodyguard  ...  172817
33                                           Mother!  ...  172808
34                                         The Mummy  ...  163365
35                                     Atomic Blonde  ...  162160
36                                          I, Tonya  ...  158474
37                                            Bright  ...  157027
38                                      Darkest Hour  ...  151690
39       Valerian and the City of a Thousand Planets  ...  150677
40                                          Baywatch  ...  148679
41                                     American Made  ...  144622
42                     Transformers: The Last Knight  ...  126735

[43 rows x 5 columns]